FROM mcr.microsoft.com/playwright/python:v1.48.0-noble

WORKDIR /project

RUN apt-get update && apt-get install -y \
    python3-dev \
    python3-venv \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config

COPY . .

RUN python3 -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

RUN /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

CMD ["pytest"]